/**
 * Application Routes
 *
 * Assembles route objects exported from each page/feature.
 * Each page owns its own routes — this file just composes them.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { Outlet, type RouteObject } from 'react-router-dom'
import { AuthGuard } from '@/router/auth-guard'
import { MainLayout } from '@/router/layouts/main-layout'
import { AuthLayoutWrapper } from '@/router/layouts/auth-layout'
import { RouteErrorBoundary } from '@/router/error-boundary'
import NotFoundPage from '@/shared/components/not-found-page'
import { LandingLayout } from '@/router/layouts/landing-layout'
import { landingRoutes } from '@/pages/landing'
import { agentsRoutes } from '@/pages/agents'
import { manifestoRoutes } from '@/pages/manifesto'
import { communityRoutes } from '@/pages/community'
import { dashboardRoutes } from '@/pages/dashboard'
import { authRoutes } from '@/features/auth'
import { legalRoutes } from '@/pages/legal'
// blacksmith:import

/**
 * Private routes — wrapped in AuthGuard, requires authentication.
 * Add your authenticated routes here.
 */
const privateRoutes: RouteObject[] = [
  ...dashboardRoutes,
  // blacksmith:routes
]

export const routes: RouteObject[] = [
  // Landing & marketing pages — full-bleed, own nav/footer
  {
    element: <LandingLayout />,
    errorElement: <RouteErrorBoundary />,
    children: [
      ...landingRoutes,
      ...agentsRoutes,
      ...manifestoRoutes,
      ...communityRoutes,
    ],
  },

  // Auth pages (login, register, etc.)
  {
    element: <AuthLayoutWrapper />,
    errorElement: <RouteErrorBoundary />,
    children: authRoutes,
  },

  // App pages (authenticated shell)
  {
    element: <MainLayout />,
    errorElement: <RouteErrorBoundary />,
    children: [
      {
        element: (
          <AuthGuard>
            <Outlet />
          </AuthGuard>
        ),
        children: privateRoutes,
      },
    ],
  },

  // Legal pages — own full-page layout
  ...legalRoutes.map((route) => ({ ...route, errorElement: <RouteErrorBoundary /> })),

  // Catch-all 404
  { path: '*', element: <NotFoundPage /> },
]
